### ISSUE TITLE
error: No compatible binary build found for this package

### ISSUE THREAD

**Issue by puruzio** [fabien-h/meteor-radium#1]
As I'm trying to add this package to my meteor app on Windows 8.1, I get the above message.

It also says "Contact the package author and ask them to publish it for your platform."

**Comment by fabien-h** [comment]
Oh crap, don't use this package, :(

It was a test to see how to deploy a package on atmosphere... But apparently, there is no way to delete it now. Sorry.

But you don't really need a package to do that, just take the code and use it standalone.

**Comment by puruzio** [comment]
Sorry for a newbie question, but what do you mean by "use it standalone"? Include it in the script folder? I tried but got "Uncaught ReferenceError: Radium is not defined" error.

**Comment by fabien-h** [comment]
It means nothing. I meant "just go for regular code": add broserify package, npm radium package and then require radium.

**Comment by puruzio** [comment]
Sorry for bothering you again. I loaded Radium following instructions here http://react-in-meteor.readthedocs.org/en/latest/client-npm/

Radium = require("radium"); in app.browserify.js

However when I try to use Radium in the js, my inline css doesn't work. Chrome dev tool indicates that Radium = module.exports(ComposedComponent). 

I'm assuming this should be an object, considering that ReactPIXI that I loaded the same way, works just fine, and the dev tool says ReactPIXI = Object {factories: Object}.

Can you please help?

**Comment by puruzio** [comment]
FYI. Also posted the question here.http://stackoverflow.com/questions/31717521/using-npm-package-in-meteor-via-cosmosbrowserify
